#pragma once

#include "native_library.hpp"

#include <FusionCutter/PluginApi.h>

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <limits>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace fc::catalog {

// Plugin admission budgets bound contribution count, copied metadata, and diagnostics supplied by callbacks.
inline constexpr std::size_t kPluginMetadataByteCapacity = 2U * 1024U * 1024U;
inline constexpr std::size_t kExternalCandidateCapacity = 128;
inline constexpr std::size_t kGlobalDefinitionCapacity = 4096;
inline constexpr std::size_t kCallbackErrorByteCapacity = 1024;

// Origin controls admission priority, cleanup ownership, and whether rejection is fatal.
enum class PluginOrigin {
    Core,
    Bundled,
    External,
};

// The stage identifies which forward-only admission boundary rejected a contribution.
enum class AdmissionStage {
    Discovery,
    Architecture,
    Loading,
    Query,
    Registration,
    Copying,
    Structure,
    Collision,
    Capacity,
    Configuration,
};

// Identifies one rejected contribution at the stage that owns the failure; plugin rejection remains nonfatal.
struct RejectionRecord {
    std::optional<std::filesystem::path> path;
    std::optional<std::string> plugin_id;
    AdmissionStage stage{};
    std::string reason;
    std::string operation;
};

// Framework-owned deep copies of the fixed-depth registration tree contain no pointers into plugin metadata.
struct SettingDefinitionRecord {
    std::string section;
    std::string key;
    std::string description;
    std::string environment;
    FC_SettingType type{};
    FC_Bool has_range{};
    FC_SettingValue default_value{};
    FC_SettingValue minimum{};
    FC_SettingValue maximum{};
    std::string default_string;
    std::uint32_t max_length{};
    bool choices_pointer_present{};
    std::vector<std::string> choices;
};

struct SupportDefinitionRecord {
    FC_TargetLayout layouts{};
    FC_HostRole roles{};
    FC_TargetImage image{};
    FC_PatchCallbacks callbacks{};
    FC_Bool has_settings{};
    bool settings_pointer_present{};
    std::vector<SettingDefinitionRecord> settings;
    std::vector<std::string> depends_on;
    std::vector<std::string> includes;
    FC_FailurePolicy failure_policy{};
};

struct PatchDefinitionRecord {
    std::string id;
    std::string name;
    std::string description;
    std::string version;
    std::string author;
    std::string source;
    FC_Bool configurable{};
    FC_Bool enabled{};
    std::string category;
    FC_FailurePolicy failure_policy{};
    std::vector<SettingDefinitionRecord> settings;
    std::vector<std::string> depends_on;
    std::vector<std::string> includes;
    std::vector<SupportDefinitionRecord> supports;
    // The target match moves with the definition; null means NotApplicable in this plugin catalog.
    std::optional<std::uint32_t> selected_support;
};

struct GroupDefinitionRecord {
    std::string id;
    std::vector<std::string> members;
    FC_Bool configurable{};
    FC_Bool enabled{};
    std::string category;
    std::string description;
};

struct CategoryDefinitionRecord {
    std::string id;
    FC_Bool has_order{};
    std::uint32_t order{};
};

struct PluginDefinitionRecord {
    std::string id;
    std::string version;
    std::string author;
    std::string source;
    std::vector<CategoryDefinitionRecord> categories;
    std::vector<GroupDefinitionRecord> groups;
    std::vector<PatchDefinitionRecord> patches;

    [[nodiscard]] std::size_t definition_count() const noexcept {
        return groups.size() + patches.size();
    }
};

using RegistrationReleaseFn = void (*)() noexcept;

// Couples an in-process registration entry with cleanup for the SDK state that owns retained callback objects.
struct RegistrationBridge {
    FC_RegisterPluginFn register_plugin{};
    RegistrationReleaseFn release{};
};

// Owns registration state generated by the SDK for a built-in or bundled plugin until rejection or final transfer.
class RegistrationOwner {
  public:
    RegistrationOwner() = default;
    explicit RegistrationOwner(RegistrationReleaseFn release) noexcept;
    RegistrationOwner(const RegistrationOwner&) = delete;
    RegistrationOwner& operator=(const RegistrationOwner&) = delete;
    RegistrationOwner(RegistrationOwner&& other) noexcept;
    RegistrationOwner& operator=(RegistrationOwner&& other) noexcept;
    ~RegistrationOwner();

  private:
    void reset() noexcept;

    RegistrationReleaseFn release_{};
};

// Owns an acquired contribution and every resource needed while it advances through admission.
struct ProvisionalPlugin {
    PluginOrigin origin{};
    std::size_t acquisition_order{};
    std::uint32_t sdk_revision{};

    // These owners precede copied definitions so reverse destruction removes every callback before code/state.
    RegistrationOwner registration_owner;
    std::optional<NativeLibrary> library;
    CodeOwner code_owner;
    PluginDefinitionRecord definition;

    ProvisionalPlugin() = default;
    ProvisionalPlugin(const ProvisionalPlugin&) = delete;
    ProvisionalPlugin& operator=(const ProvisionalPlugin&) = delete;
    ProvisionalPlugin(ProvisionalPlugin&&) noexcept = default;
    ProvisionalPlugin& operator=(ProvisionalPlugin&&) noexcept = default;
};

// Dense indices are assigned once when final ownership is established and never rekeyed.
struct PatchIndex {
    std::uint32_t value{};

    friend bool operator==(PatchIndex, PatchIndex) = default;
};

// Report tokens encode only a dense patch index in the plugin catalog and never borrow plugin-owned storage.
[[nodiscard]] inline FC_ReportToken report_token(PatchIndex patch) noexcept {
    return reinterpret_cast<FC_ReportToken>(static_cast<std::uintptr_t>(patch.value) + 1);
}

// A malformed or null token remains outside the plugin catalog and receives framework diagnostic attribution.
[[nodiscard]] inline std::optional<PatchIndex> patch_from_report(FC_ReportToken report) noexcept {
    const auto encoded = reinterpret_cast<std::uintptr_t>(report);
    if (encoded == 0 || encoded - 1 > std::numeric_limits<std::uint32_t>::max()) {
        return std::nullopt;
    }
    return PatchIndex{static_cast<std::uint32_t>(encoded - 1)};
}

struct PluginIndex {
    std::uint32_t value{};

    friend bool operator==(PluginIndex, PluginIndex) = default;
};

struct GroupIndex {
    std::uint32_t value{};

    friend bool operator==(GroupIndex, GroupIndex) = default;
};

// Final records intentionally discard provisional origin and acquisition order.
struct PluginRecord {
    std::uint32_t sdk_revision{};
    RegistrationOwner registration_owner;
    std::optional<NativeLibrary> library;
    // Plan callback thunks must remain in this executable extent for the lifetime of their copied record.
    CodeOwner code_owner;
    PluginDefinitionRecord definition;

    PluginRecord() = default;
    PluginRecord(const PluginRecord&) = delete;
    PluginRecord& operator=(const PluginRecord&) = delete;
    PluginRecord(PluginRecord&&) noexcept = default;
    PluginRecord& operator=(PluginRecord&&) noexcept = default;
};

// The immutable plugin catalog owns admitted definitions and callback code for process lifetime.
class Catalog {
  public:
    // Takes process-lifetime ownership and builds the complete case-insensitive lookup index once.
    explicit Catalog(std::vector<PluginRecord> plugins);

    // Lookups return stable dense indices into this immutable plugin catalog.
    [[nodiscard]] std::span<const PluginRecord> plugins() const noexcept;
    [[nodiscard]] std::size_t patch_count() const noexcept;
    [[nodiscard]] std::size_t group_count() const noexcept;
    [[nodiscard]] std::optional<PluginIndex> find_plugin(std::string_view id) const;
    [[nodiscard]] std::optional<PatchIndex> find_patch(std::string_view id) const;
    [[nodiscard]] std::optional<GroupIndex> find_group(std::string_view id) const;
    // Dense indices from this plugin catalog are required; foreign or unchecked indices are invalid.
    [[nodiscard]] const PatchDefinitionRecord& patch(PatchIndex index) const noexcept;
    [[nodiscard]] const GroupDefinitionRecord& group(GroupIndex index) const noexcept;
    // Location accessors preserve alignment with ConfigurationSnapshot without rebuilding an ownership index.
    [[nodiscard]] PluginIndex patch_plugin(PatchIndex index) const noexcept;
    [[nodiscard]] std::uint32_t patch_ordinal(PatchIndex index) const noexcept;
    [[nodiscard]] PluginIndex group_plugin(GroupIndex index) const noexcept;
    [[nodiscard]] std::uint32_t group_ordinal(GroupIndex index) const noexcept;
    [[nodiscard]] const PluginRecord& plugin(PluginIndex index) const noexcept;

  private:
    struct PatchLocation {
        std::uint32_t plugin{};
        std::uint32_t patch{};
    };

    struct GroupLocation {
        std::uint32_t plugin{};
        std::uint32_t group{};
    };

    std::vector<PluginRecord> plugins_;
    std::vector<PatchLocation> patches_;
    std::vector<GroupLocation> groups_;
    std::unordered_map<std::string, PluginIndex> plugin_by_id_;
    std::unordered_map<std::string, PatchIndex> patch_by_id_;
    std::unordered_map<std::string, GroupIndex> group_by_id_;
};

} // namespace fc::catalog
