#pragma once

#include "catalog_types.hpp"

#include <span>

namespace fc::catalog {

// References the bridge table generated by CMake, whose storage remains valid for the process lifetime.
[[nodiscard]] std::span<const RegistrationBridge> configured_bundle_bridges() noexcept;

} // namespace fc::catalog
