include_guard(GLOBAL)

function(_fc_validate_patch_tokens label allowed)
    foreach(token IN LISTS ARGN)
        if(NOT token IN_LIST allowed)
            message(FATAL_ERROR "${label} contains unsupported value '${token}'.")
        endif()
    endforeach()
endfunction()

function(_fc_patch_roles_match roles output)
    if(FC_CORE_ROLE STREQUAL "Universal")
        set(matches TRUE)
    elseif(FC_CORE_ROLE STREQUAL "Client" AND "CLIENT" IN_LIST roles)
        set(matches TRUE)
    elseif(FC_CORE_ROLE STREQUAL "Server" AND "SERVER" IN_LIST roles)
        set(matches TRUE)
    else()
        set(matches FALSE)
    endif()
    set(${output} ${matches} PARENT_SCOPE)
endfunction()

function(_fc_patch_architectures_match architectures output)
    string(TOUPPER "${FC_ARCHITECTURE}" current_architecture)
    if(current_architecture IN_LIST architectures)
        set(matches TRUE)
    else()
        set(matches FALSE)
    endif()
    set(${output} ${matches} PARENT_SCOPE)
endfunction()

function(fc_patch)
    cmake_parse_arguments(PARSE_ARGV 0 patch "" "ID;DEFINITION" "ARCHITECTURES;ROLES;SOURCES")
    foreach(argument IN ITEMS ID DEFINITION ARCHITECTURES ROLES SOURCES)
        if(NOT patch_${argument})
            message(FATAL_ERROR "fc_patch requires ${argument}.")
        endif()
    endforeach()

    set(allowed_architectures X86 X64)
    set(allowed_roles CLIENT SERVER)
    _fc_validate_patch_tokens("Patch ${patch_ID} architectures" "${allowed_architectures}" ${patch_ARCHITECTURES})
    _fc_validate_patch_tokens("Patch ${patch_ID} roles" "${allowed_roles}" ${patch_ROLES})

    get_property(ids GLOBAL PROPERTY FC_PATCH_IDS)
    if(patch_ID IN_LIST ids)
        message(FATAL_ERROR "Duplicate patch ID '${patch_ID}'.")
    endif()

    get_property(manifest_directory GLOBAL PROPERTY FC_CURRENT_PATCH_DIRECTORY)
    if(NOT manifest_directory)
        message(FATAL_ERROR "fc_patch may only be used from a discovered patch.cmake manifest.")
    endif()

    set(sources ${patch_SOURCES})
    list(TRANSFORM sources PREPEND "${manifest_directory}/")
    set_property(GLOBAL APPEND PROPERTY FC_PATCH_IDS "${patch_ID}")
    set_property(GLOBAL PROPERTY "FC_PATCH_${patch_ID}_DEFINITION" "${patch_DEFINITION}")
    set_property(GLOBAL PROPERTY "FC_PATCH_${patch_ID}_ARCHITECTURES" "${patch_ARCHITECTURES}")
    set_property(GLOBAL PROPERTY "FC_PATCH_${patch_ID}_ROLES" "${patch_ROLES}")
    set_property(GLOBAL PROPERTY "FC_PATCH_${patch_ID}_SOURCES" "${sources}")
    set_property(GLOBAL PROPERTY "FC_PATCH_${patch_ID}_GROUP_COUNT" 0)
endfunction()

function(fc_patch_sources)
    cmake_parse_arguments(PARSE_ARGV 0 group "" "PATCH" "ARCHITECTURES;ROLES;SOURCES")
    foreach(argument IN ITEMS PATCH ARCHITECTURES ROLES SOURCES)
        if(NOT group_${argument})
            message(FATAL_ERROR "fc_patch_sources requires ${argument}.")
        endif()
    endforeach()

    set(allowed_architectures X86 X64)
    set(allowed_roles CLIENT SERVER)
    _fc_validate_patch_tokens("Patch ${group_PATCH} source-group architectures" "${allowed_architectures}"
                              ${group_ARCHITECTURES})
    _fc_validate_patch_tokens("Patch ${group_PATCH} source-group roles" "${allowed_roles}" ${group_ROLES})

    get_property(ids GLOBAL PROPERTY FC_PATCH_IDS)
    if(NOT group_PATCH IN_LIST ids)
        message(FATAL_ERROR "fc_patch_sources references unknown patch '${group_PATCH}'.")
    endif()
    get_property(manifest_directory GLOBAL PROPERTY FC_CURRENT_PATCH_DIRECTORY)
    get_property(group_count GLOBAL PROPERTY "FC_PATCH_${group_PATCH}_GROUP_COUNT")
    math(EXPR group_count "${group_count} + 1")

    set(sources ${group_SOURCES})
    list(TRANSFORM sources PREPEND "${manifest_directory}/")
    set_property(GLOBAL PROPERTY "FC_PATCH_${group_PATCH}_GROUP_COUNT" ${group_count})
    set_property(GLOBAL PROPERTY "FC_PATCH_${group_PATCH}_GROUP_${group_count}_ARCHITECTURES"
                 "${group_ARCHITECTURES}")
    set_property(GLOBAL PROPERTY "FC_PATCH_${group_PATCH}_GROUP_${group_count}_ROLES" "${group_ROLES}")
    set_property(GLOBAL PROPERTY "FC_PATCH_${group_PATCH}_GROUP_${group_count}_SOURCES" "${sources}")
endfunction()

function(_fc_definition_declaration definition output)
    string(REPLACE "::" ";" parts "${definition}")
    list(POP_BACK parts function_name)

    set(declaration "")
    foreach(namespace_name IN LISTS parts)
        string(APPEND declaration "namespace ${namespace_name} {\n")
    endforeach()
    string(APPEND declaration "fusioncutter::PatchDefinition ${function_name}();\n")
    list(REVERSE parts)
    foreach(namespace_name IN LISTS parts)
        string(APPEND declaration "} // namespace ${namespace_name}\n")
    endforeach()
    set(${output} "${declaration}" PARENT_SCOPE)
endfunction()

function(fc_generate_patch_catalog)
    cmake_parse_arguments(PARSE_ARGV 0 catalog "" "PATCH_ROOT;OUTPUT;OUT_SOURCES" "")
    foreach(argument IN ITEMS PATCH_ROOT OUTPUT OUT_SOURCES)
        if(NOT catalog_${argument})
            message(FATAL_ERROR "fc_generate_patch_catalog requires ${argument}.")
        endif()
    endforeach()

    set_property(GLOBAL PROPERTY FC_PATCH_IDS "")
    file(GLOB_RECURSE manifests CONFIGURE_DEPENDS "${catalog_PATCH_ROOT}/patch.cmake")
    list(SORT manifests)
    foreach(manifest IN LISTS manifests)
        get_filename_component(manifest_directory "${manifest}" DIRECTORY)
        set_property(GLOBAL PROPERTY FC_CURRENT_PATCH_DIRECTORY "${manifest_directory}")
        include("${manifest}")
    endforeach()
    set_property(GLOBAL PROPERTY FC_CURRENT_PATCH_DIRECTORY "")

    get_property(ids GLOBAL PROPERTY FC_PATCH_IDS)
    list(SORT ids)
    set(patch_sources)
    set(declarations)
    set(entries)
    foreach(id IN LISTS ids)
        get_property(definition GLOBAL PROPERTY "FC_PATCH_${id}_DEFINITION")
        get_property(architectures GLOBAL PROPERTY "FC_PATCH_${id}_ARCHITECTURES")
        get_property(roles GLOBAL PROPERTY "FC_PATCH_${id}_ROLES")
        _fc_patch_architectures_match("${architectures}" architecture_matches)
        _fc_patch_roles_match("${roles}" role_matches)
        if(NOT architecture_matches OR NOT role_matches)
            continue()
        endif()

        get_property(sources GLOBAL PROPERTY "FC_PATCH_${id}_SOURCES")
        list(APPEND patch_sources ${sources})
        get_property(group_count GLOBAL PROPERTY "FC_PATCH_${id}_GROUP_COUNT")
        if(group_count GREATER 0)
            foreach(group_index RANGE 1 ${group_count})
                get_property(group_architectures GLOBAL PROPERTY
                             "FC_PATCH_${id}_GROUP_${group_index}_ARCHITECTURES")
                get_property(group_roles GLOBAL PROPERTY "FC_PATCH_${id}_GROUP_${group_index}_ROLES")
                _fc_patch_architectures_match("${group_architectures}" group_architecture_matches)
                _fc_patch_roles_match("${group_roles}" group_role_matches)
                if(group_architecture_matches AND group_role_matches)
                    get_property(group_sources GLOBAL PROPERTY "FC_PATCH_${id}_GROUP_${group_index}_SOURCES")
                    list(APPEND patch_sources ${group_sources})
                endif()
            endforeach()
        endif()

        _fc_definition_declaration("${definition}" declaration)
        string(APPEND declarations "\n${declaration}")

        set(x86 false)
        set(x64 false)
        set(client false)
        set(server false)
        if("X86" IN_LIST architectures)
            set(x86 true)
        endif()
        if("X64" IN_LIST architectures)
            set(x64 true)
        endif()
        if("CLIENT" IN_LIST roles)
            set(client true)
        endif()
        if("SERVER" IN_LIST roles)
            set(server true)
        endif()
        string(APPEND entries
               "        catalog_entry(\"${id}\", ${definition}(), PatchBuildEnvelope{${x86}, ${x64}, ${client}, ${server}}),\n")
    endforeach()

    get_filename_component(output_directory "${catalog_OUTPUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    if(entries)
        set(FC_PATCH_ENTRIES "\n${entries}    ")
    else()
        set(FC_PATCH_ENTRIES "")
    endif()
    set(FC_PATCH_DECLARATIONS "${declarations}")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/patch_catalog.cpp.in" "${catalog_OUTPUT}" @ONLY)

    set(${catalog_OUT_SOURCES} ${patch_sources} PARENT_SCOPE)
endfunction()
